In [21]:
import numpy as np


from keras.preprocessing.image import load_img, img_to_array

from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from keras import models
from keras import layers
from tensorflow.keras import Model
from keras import optimizers
from tensorflow.keras.applications.mobilenet_v2 import MobileNetV2, preprocess_input

In [14]:
modelo = MobileNetV2(
    input_shape=None,
    alpha=1.0,
    weights=None,
    input_tensor=None,
    pooling=None,
    classes=2,
    classifier_activation='softmax'
)

In [16]:
train = ImageDataGenerator(rescale = 1./255)
test = ImageDataGenerator(rescale = 1./255)
val = ImageDataGenerator(rescale = 1./255)

In [38]:
training_set = train.flow_from_directory('train',
                                         target_size=(200,200),
                                         batch_size = 15,
                                         class_mode = 'binary',
                                         color_mode='rgb'
                                        )


Found 970 images belonging to 2 classes.


In [40]:
modelo.output

<KerasTensor shape=(None, 2), dtype=float32, sparse=False, ragged=False, name=keras_tensor_935>

In [29]:
model = Model(inputs = modelo.input, outputs = preds)

ValueError: All `outputs` values must be KerasTensors. Received: outputs=[[[[0.50129485 0.3431547 ]
   [0.5013971  0.3316958 ]
   [0.50136304 0.33549416]
   ...
   [0.50107336 0.36860448]
   [0.5013971  0.3316958 ]
   [0.50136304 0.33549416]]

  [[0.50146526 0.32416487]
   [0.5013801  0.33359227]
   [0.50120974 0.35284618]
   ...
   [0.50146526 0.32416487]
   [0.50132895 0.33931395]
   [0.5016015  0.30937544]]

  [[0.501346   0.3374014 ]
   [0.5012609  0.3470162 ]
   [0.5012609  0.3470162 ]
   ...
   [0.5010904  0.36661848]
   [0.5014311  0.32791927]
   [0.5013801  0.33359227]]

  ...

  [[0.50136304 0.33549416]
   [0.50120974 0.35284618]
   [0.5013119  0.3412317 ]
   ...
   [0.5014993  0.32043296]
   [0.50146526 0.32416487]
   [0.5013801  0.33359227]]

  [[0.5013971  0.3316958 ]
   [0.5013119  0.3412317 ]
   [0.5013801  0.33359227]
   ...
   [0.5014142  0.32980478]
   [0.50132895 0.33931395]
   [0.50144815 0.32603925]]

  [[0.50144815 0.32603925]
   [0.5013801  0.33359227]
   [0.50148225 0.3222961 ]
   ...
   [0.50146526 0.32416487]
   [0.5014142  0.32980478]
   [0.50161856 0.3075531 ]]]


 [[[0.50146526 0.32416487]
   [0.5011756  0.35675737]
   [0.5015675  0.3130379 ]
   ...
   [0.50148225 0.3222961 ]
   [0.50151634 0.31857556]
   [0.501823   0.28616166]]

  [[0.5013801  0.33359227]
   [0.5013801  0.33359227]
   [0.50155044 0.314878  ]
   ...
   [0.50165266 0.3039264 ]
   [0.5015675  0.3130379 ]
   [0.50132895 0.33931395]]

  [[0.50110745 0.364637  ]
   [0.50146526 0.32416487]
   [0.5014311  0.32791927]
   ...
   [0.50168675 0.3003239 ]
   [0.50173783 0.29496625]
   [0.50148225 0.3222961 ]]

  ...

  [[0.5013801  0.33359227]
   [0.5013119  0.3412317 ]
   [0.5016356  0.30573675]
   ...
   [0.5016015  0.30937544]
   [0.50148225 0.3222961 ]
   [0.50122666 0.35089785]]

  [[0.5016697  0.30212212]
   [0.5016015  0.30937544]
   [0.5013801  0.33359227]
   ...
   [0.5014142  0.32980478]
   [0.5013119  0.3412317 ]
   [0.50097114 0.38061225]]

  [[0.50148225 0.3222961 ]
   [0.50168675 0.3003239 ]
   [0.5012778  0.34508294]
   ...
   [0.50124377 0.3489545 ]
   [0.50168675 0.3003239 ]
   [0.50155044 0.314878  ]]]


 [[[0.5011586  0.3587202 ]
   [0.5013801  0.33359227]
   [0.5011586  0.3587202 ]
   ...
   [0.5012778  0.34508294]
   [0.50120974 0.35284618]
   [0.5014142  0.32980478]]

  [[0.5011926  0.35479936]
   [0.5012778  0.34508294]
   [0.5014142  0.32980478]
   ...
   [0.5011756  0.35675737]
   [0.5013119  0.3412317 ]
   [0.50136304 0.33549416]]

  [[0.50148225 0.3222961 ]
   [0.50136304 0.33549416]
   [0.50129485 0.3431547 ]
   ...
   [0.50124377 0.3489545 ]
   [0.5013119  0.3412317 ]
   [0.5012778  0.34508294]]

  ...

  [[0.5016015  0.30937544]
   [0.50144815 0.32603925]
   [0.5011586  0.3587202 ]
   ...
   [0.50151634 0.31857556]
   [0.5014142  0.32980478]
   [0.5014993  0.32043296]]

  [[0.5010904  0.36661848]
   [0.50120974 0.35284618]
   [0.50158453 0.31120372]
   ...
   [0.50122666 0.35089785]
   [0.50148225 0.3222961 ]
   [0.5013971  0.3316958 ]]

  [[0.50122666 0.35089785]
   [0.50120974 0.35284618]
   [0.5012778  0.34508294]
   ...
   [0.5010393  0.3725899 ]
   [0.50132895 0.33931395]
   [0.5011586  0.3587202 ]]]


 ...


 [[[0.5012609  0.3470162 ]
   [0.5013971  0.3316958 ]
   [0.5013971  0.3316958 ]
   ...
   [0.50129485 0.3431547 ]
   [0.50148225 0.3222961 ]
   [0.50151634 0.31857556]]

  [[0.50136304 0.33549416]
   [0.5013801  0.33359227]
   [0.5012778  0.34508294]
   ...
   [0.5013119  0.3412317 ]
   [0.5013119  0.3412317 ]
   [0.50129485 0.3431547 ]]

  [[0.50146526 0.32416487]
   [0.501346   0.3374014 ]
   [0.50114155 0.3606878 ]
   ...
   [0.50114155 0.3606878 ]
   [0.50132895 0.33931395]
   [0.5013801  0.33359227]]

  ...

  [[0.5011586  0.3587202 ]
   [0.5014142  0.32980478]
   [0.5012609  0.3470162 ]
   ...
   [0.5013119  0.3412317 ]
   [0.5013971  0.3316958 ]
   [0.5012778  0.34508294]]

  [[0.50136304 0.33549416]
   [0.50129485 0.3431547 ]
   [0.50132895 0.33931395]
   ...
   [0.50144815 0.32603925]
   [0.50155044 0.314878  ]
   [0.50122666 0.35089785]]

  [[0.5015334  0.31672385]
   [0.50129485 0.3431547 ]
   [0.50136304 0.33549416]
   ...
   [0.5015334  0.31672385]
   [0.5015675  0.3130379 ]
   [0.5011245  0.36266008]]]


 [[[0.50122666 0.35089785]
   [0.501346   0.3374014 ]
   [0.5012609  0.3470162 ]
   ...
   [0.5013801  0.33359227]
   [0.5011926  0.35479936]
   [0.50088596 0.3907322 ]]

  [[0.5014311  0.32791927]
   [0.501346   0.3374014 ]
   [0.50107336 0.36860448]
   ...
   [0.5012778  0.34508294]
   [0.50136304 0.33549416]
   [0.50132895 0.33931395]]

  [[0.50122666 0.35089785]
   [0.50110745 0.364637  ]
   [0.5013119  0.3412317 ]
   ...
   [0.5012778  0.34508294]
   [0.5012609  0.3470162 ]
   [0.50095403 0.3826283 ]]

  ...

  [[0.50107336 0.36860448]
   [0.501346   0.3374014 ]
   [0.50102234 0.37458912]
   ...
   [0.5010563  0.37059498]
   [0.50059634 0.42580077]
   [0.5010904  0.36661848]]

  [[0.5010563  0.37059498]
   [0.50132895 0.33931395]
   [0.50136304 0.33549416]
   ...
   [0.50120974 0.35284618]
   [0.5012778  0.34508294]
   [0.5011926  0.35479936]]

  [[0.50132895 0.33931395]
   [0.5011245  0.36266008]
   [0.5011756  0.35675737]
   ...
   [0.5011756  0.35675737]
   [0.5013119  0.3412317 ]
   [0.50132895 0.33931395]]]


 [[[0.501346   0.3374014 ]
   [0.50151634 0.31857556]
   [0.50148225 0.3222961 ]
   ...
   [0.5013971  0.3316958 ]
   [0.5015334  0.31672385]
   [0.5013971  0.3316958 ]]

  [[0.5014993  0.32043296]
   [0.5015334  0.31672385]
   [0.50146526 0.32416487]
   ...
   [0.50148225 0.3222961 ]
   [0.5014993  0.32043296]
   [0.5013801  0.33359227]]

  [[0.50120974 0.35284618]
   [0.50158453 0.31120372]
   [0.50165266 0.3039264 ]
   ...
   [0.5016015  0.30937544]
   [0.5012609  0.3470162 ]
   [0.5013801  0.33359227]]

  ...

  [[0.5014142  0.32980478]
   [0.50100523 0.37659255]
   [0.50129485 0.3431547 ]
   ...
   [0.50148225 0.3222961 ]
   [0.5014311  0.32791927]
   [0.50155044 0.314878  ]]

  [[0.5013801  0.33359227]
   [0.50151634 0.31857556]
   [0.50114155 0.3606878 ]
   ...
   [0.50161856 0.3075531 ]
   [0.50155044 0.314878  ]
   [0.50102234 0.37458912]]

  [[0.5016015  0.30937544]
   [0.50158453 0.31120372]
   [0.5015334  0.31672385]
   ...
   [0.5011756  0.35675737]
   [0.50114155 0.3606878 ]
   [0.5013801  0.33359227]]]] including invalid value [[[[0.50129485 0.3431547 ]
   [0.5013971  0.3316958 ]
   [0.50136304 0.33549416]
   ...
   [0.50107336 0.36860448]
   [0.5013971  0.3316958 ]
   [0.50136304 0.33549416]]

  [[0.50146526 0.32416487]
   [0.5013801  0.33359227]
   [0.50120974 0.35284618]
   ...
   [0.50146526 0.32416487]
   [0.50132895 0.33931395]
   [0.5016015  0.30937544]]

  [[0.501346   0.3374014 ]
   [0.5012609  0.3470162 ]
   [0.5012609  0.3470162 ]
   ...
   [0.5010904  0.36661848]
   [0.5014311  0.32791927]
   [0.5013801  0.33359227]]

  ...

  [[0.50136304 0.33549416]
   [0.50120974 0.35284618]
   [0.5013119  0.3412317 ]
   ...
   [0.5014993  0.32043296]
   [0.50146526 0.32416487]
   [0.5013801  0.33359227]]

  [[0.5013971  0.3316958 ]
   [0.5013119  0.3412317 ]
   [0.5013801  0.33359227]
   ...
   [0.5014142  0.32980478]
   [0.50132895 0.33931395]
   [0.50144815 0.32603925]]

  [[0.50144815 0.32603925]
   [0.5013801  0.33359227]
   [0.50148225 0.3222961 ]
   ...
   [0.50146526 0.32416487]
   [0.5014142  0.32980478]
   [0.50161856 0.3075531 ]]]


 [[[0.50146526 0.32416487]
   [0.5011756  0.35675737]
   [0.5015675  0.3130379 ]
   ...
   [0.50148225 0.3222961 ]
   [0.50151634 0.31857556]
   [0.501823   0.28616166]]

  [[0.5013801  0.33359227]
   [0.5013801  0.33359227]
   [0.50155044 0.314878  ]
   ...
   [0.50165266 0.3039264 ]
   [0.5015675  0.3130379 ]
   [0.50132895 0.33931395]]

  [[0.50110745 0.364637  ]
   [0.50146526 0.32416487]
   [0.5014311  0.32791927]
   ...
   [0.50168675 0.3003239 ]
   [0.50173783 0.29496625]
   [0.50148225 0.3222961 ]]

  ...

  [[0.5013801  0.33359227]
   [0.5013119  0.3412317 ]
   [0.5016356  0.30573675]
   ...
   [0.5016015  0.30937544]
   [0.50148225 0.3222961 ]
   [0.50122666 0.35089785]]

  [[0.5016697  0.30212212]
   [0.5016015  0.30937544]
   [0.5013801  0.33359227]
   ...
   [0.5014142  0.32980478]
   [0.5013119  0.3412317 ]
   [0.50097114 0.38061225]]

  [[0.50148225 0.3222961 ]
   [0.50168675 0.3003239 ]
   [0.5012778  0.34508294]
   ...
   [0.50124377 0.3489545 ]
   [0.50168675 0.3003239 ]
   [0.50155044 0.314878  ]]]


 [[[0.5011586  0.3587202 ]
   [0.5013801  0.33359227]
   [0.5011586  0.3587202 ]
   ...
   [0.5012778  0.34508294]
   [0.50120974 0.35284618]
   [0.5014142  0.32980478]]

  [[0.5011926  0.35479936]
   [0.5012778  0.34508294]
   [0.5014142  0.32980478]
   ...
   [0.5011756  0.35675737]
   [0.5013119  0.3412317 ]
   [0.50136304 0.33549416]]

  [[0.50148225 0.3222961 ]
   [0.50136304 0.33549416]
   [0.50129485 0.3431547 ]
   ...
   [0.50124377 0.3489545 ]
   [0.5013119  0.3412317 ]
   [0.5012778  0.34508294]]

  ...

  [[0.5016015  0.30937544]
   [0.50144815 0.32603925]
   [0.5011586  0.3587202 ]
   ...
   [0.50151634 0.31857556]
   [0.5014142  0.32980478]
   [0.5014993  0.32043296]]

  [[0.5010904  0.36661848]
   [0.50120974 0.35284618]
   [0.50158453 0.31120372]
   ...
   [0.50122666 0.35089785]
   [0.50148225 0.3222961 ]
   [0.5013971  0.3316958 ]]

  [[0.50122666 0.35089785]
   [0.50120974 0.35284618]
   [0.5012778  0.34508294]
   ...
   [0.5010393  0.3725899 ]
   [0.50132895 0.33931395]
   [0.5011586  0.3587202 ]]]


 ...


 [[[0.5012609  0.3470162 ]
   [0.5013971  0.3316958 ]
   [0.5013971  0.3316958 ]
   ...
   [0.50129485 0.3431547 ]
   [0.50148225 0.3222961 ]
   [0.50151634 0.31857556]]

  [[0.50136304 0.33549416]
   [0.5013801  0.33359227]
   [0.5012778  0.34508294]
   ...
   [0.5013119  0.3412317 ]
   [0.5013119  0.3412317 ]
   [0.50129485 0.3431547 ]]

  [[0.50146526 0.32416487]
   [0.501346   0.3374014 ]
   [0.50114155 0.3606878 ]
   ...
   [0.50114155 0.3606878 ]
   [0.50132895 0.33931395]
   [0.5013801  0.33359227]]

  ...

  [[0.5011586  0.3587202 ]
   [0.5014142  0.32980478]
   [0.5012609  0.3470162 ]
   ...
   [0.5013119  0.3412317 ]
   [0.5013971  0.3316958 ]
   [0.5012778  0.34508294]]

  [[0.50136304 0.33549416]
   [0.50129485 0.3431547 ]
   [0.50132895 0.33931395]
   ...
   [0.50144815 0.32603925]
   [0.50155044 0.314878  ]
   [0.50122666 0.35089785]]

  [[0.5015334  0.31672385]
   [0.50129485 0.3431547 ]
   [0.50136304 0.33549416]
   ...
   [0.5015334  0.31672385]
   [0.5015675  0.3130379 ]
   [0.5011245  0.36266008]]]


 [[[0.50122666 0.35089785]
   [0.501346   0.3374014 ]
   [0.5012609  0.3470162 ]
   ...
   [0.5013801  0.33359227]
   [0.5011926  0.35479936]
   [0.50088596 0.3907322 ]]

  [[0.5014311  0.32791927]
   [0.501346   0.3374014 ]
   [0.50107336 0.36860448]
   ...
   [0.5012778  0.34508294]
   [0.50136304 0.33549416]
   [0.50132895 0.33931395]]

  [[0.50122666 0.35089785]
   [0.50110745 0.364637  ]
   [0.5013119  0.3412317 ]
   ...
   [0.5012778  0.34508294]
   [0.5012609  0.3470162 ]
   [0.50095403 0.3826283 ]]

  ...

  [[0.50107336 0.36860448]
   [0.501346   0.3374014 ]
   [0.50102234 0.37458912]
   ...
   [0.5010563  0.37059498]
   [0.50059634 0.42580077]
   [0.5010904  0.36661848]]

  [[0.5010563  0.37059498]
   [0.50132895 0.33931395]
   [0.50136304 0.33549416]
   ...
   [0.50120974 0.35284618]
   [0.5012778  0.34508294]
   [0.5011926  0.35479936]]

  [[0.50132895 0.33931395]
   [0.5011245  0.36266008]
   [0.5011756  0.35675737]
   ...
   [0.5011756  0.35675737]
   [0.5013119  0.3412317 ]
   [0.50132895 0.33931395]]]


 [[[0.501346   0.3374014 ]
   [0.50151634 0.31857556]
   [0.50148225 0.3222961 ]
   ...
   [0.5013971  0.3316958 ]
   [0.5015334  0.31672385]
   [0.5013971  0.3316958 ]]

  [[0.5014993  0.32043296]
   [0.5015334  0.31672385]
   [0.50146526 0.32416487]
   ...
   [0.50148225 0.3222961 ]
   [0.5014993  0.32043296]
   [0.5013801  0.33359227]]

  [[0.50120974 0.35284618]
   [0.50158453 0.31120372]
   [0.50165266 0.3039264 ]
   ...
   [0.5016015  0.30937544]
   [0.5012609  0.3470162 ]
   [0.5013801  0.33359227]]

  ...

  [[0.5014142  0.32980478]
   [0.50100523 0.37659255]
   [0.50129485 0.3431547 ]
   ...
   [0.50148225 0.3222961 ]
   [0.5014311  0.32791927]
   [0.50155044 0.314878  ]]

  [[0.5013801  0.33359227]
   [0.50151634 0.31857556]
   [0.50114155 0.3606878 ]
   ...
   [0.50161856 0.3075531 ]
   [0.50155044 0.314878  ]
   [0.50102234 0.37458912]]

  [[0.5016015  0.30937544]
   [0.50158453 0.31120372]
   [0.5015334  0.31672385]
   ...
   [0.5011756  0.35675737]
   [0.50114155 0.3606878 ]
   [0.5013801  0.33359227]]]] of type <class 'tensorflow.python.framework.ops.EagerTensor'>

In [22]:
model.compile(loss='binary_crossentropy',
              optimizer=optimizers.Adam(learning_rate=2e-5),
              metrics=['acc'])

NameError: name 'model' is not defined